In [181]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [182]:
import pandas as pd

from functions import *

pd.set_option('display.max_columns', None)

df_merged = pd.read_csv("data/df_merged_national.csv")

In [183]:
#df_merged.loc[:87, "Year"] = df_merged["Unnamed: 45"].iloc[:88].values

# Tuve que hacer esta pirula para que el csv 202019 y 202023 se puedan concatenar

In [184]:
df_merged = clean_df(df_merged)
df_merged = every_float_to_int(df_merged)

In [185]:
df_no_provincias = df_merged[(df_merged["region"] == "    DESCONOCIDA") | (df_merged["region"] == "    EN EL EXTRANJERO") | (df_merged["region"] == "    TOTAL NACIONAL")]

df_no_provincias.to_csv("data/df_no_provincias.csv", index=False)

In [186]:
df_merged = df_merged[~df_merged.index.isin(df_no_provincias.index)]

# df_merged.to_csv("data/df_merged_national.csv", index=False)

In [187]:
df_num = df_merged.iloc[:, df_merged.columns != 'region']

In [188]:
# df_num.corr()

df_merged.head()

,region,1_against_people,11_intentional_homicides_murders,111_intentional_homicides_murders_committed,12_injuries,13_domestic_violence,14_other_crimes_against_people,2_against_freedom,21_habitual_domestic_violence,22_other_crimes_against_freedom,3_sexual_freedom,31_sexual_assault,311_sexual_assault_with_penetration,32_corruption_of_minors_or_disabled,33_child_pornography,34_other_crimes_against_sexual_freedom,4_family_relationships,5_property_crimes,51_thefts,52_robbery_with_force,521_Robos_con_fuerza_en_las_cosas_en_el_interior_de_vehículos,522_robbery_with_force_in_homes,523_robbery_with_force_in_establishments,53_robbery_with_violence_or_intimidation,531_robbery_with_violence_in_public_ways,532_robbery_with_violence_in_homes,533_robbery_with_violence_in_establishments,54_vehicle_theft,55_fraud,551_computer_fraud,56_damage,57_against_intellectual_industrial_property,58_money_laundering,59_other_property_crimes,6_collective_security,61_drug_trafficking,62_against_road_safety,63_other_collective_security_crimes,7_forgeries,8_public_administration,9_justice_administration,10_public_order,11_special_legislation,12_other_criminal_offenses,year
0,ANDALUCÍA,45636,363,71,24848,19294,1131,32765,3007,29758,3473,2044,604,74,130,621,1702,289412,95492,47977,19215,14101,5953,7676,5028,630,1195,5957,84455,72795,35037,332,106,12380,16357,4790,11043,524,6596,99,8688,5455,141,2857,2023
1,ARAGÓN,6071,47,9,2949,2967,108,3139,301,2838,511,330,92,13,21,55,179,36261,10651,5550,1044,1955,747,1076,702,65,203,318,12353,10891,5095,23,4,1191,1651,552,1049,50,743,11,1056,967,5,271,2023
2,ASTURIAS (PRINCIPADO DE),4185,21,6,2235,1861,68,2421,92,2329,325,199,67,8,14,37,95,23761,7681,2581,586,990,561,424,216,44,109,259,8907,7897,2931,9,2,967,1047,190,779,78,439,4,838,511,5,257,2023
3,BALEARS (ILLES),10159,50,8,4495,5341,273,6339,678,5661,1050,709,156,21,32,132,237,53976,23009,6806,3195,1937,738,1519,994,82,228,1832,13522,10299,4912,89,7,2280,2871,776,1892,203,912,18,1667,914,3,363,2023
4,CANARIAS,15210,77,17,7847,6765,521,11181,1078,10103,1189,750,221,31,53,134,564,66962,26245,7853,2969,2120,1249,1858,1106,148,333,1451,19297,15752,7441,107,19,2691,3725,764,2802,159,1269,25,2295,1099,10,693,2023

In [189]:
# df_merged_dummies = pd.get_dummies(df_merged, columns=["region"])

# df_merged_dummies

In [190]:
df_merged = add_coordinates_from_dict(df_merged)

In [191]:
regions = {
    "ANDALUCÍA": 0,
    "ARAGÓN": 1,
    "ASTURIAS (PRINCIPADO DE)": 2,
    "BALEARS (ILLES)": 3,
    "CANTABRIA": 4,
    "CANARIAS": 5,
    "CASTILLA - LA MANCHA": 6,
    "CASTILLA Y LEÓN": 7,
    "CATALUÑA": 8,
    "CIUDAD AUTÓNOMA DE CEUTA": 9,
    "CIUDAD AUTÓNOMA DE MELILLA": 10,
    "COMUNITAT VALENCIANA": 11,
    "EXTREMADURA": 12,
    "GALICIA": 13,
    "MADRID (COMUNIDAD DE)": 14,
    "MURCIA (REGIÓN DE)": 15,
    "NAVARRA (COMUNIDAD FORAL DE)": 16,
    "PAÍS VASCO": 17,
    "RIOJA (LA)": 18
}


df_merged["region"] = df_merged["region"].replace(regions)

C:\Users\VSPC\AppData\Local\Temp\ipykernel_9232\2512969448.py:24: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_merged["region"] = df_merged["region"].replace(regions)

In [192]:
df_merged.insert(0, "year", df_merged.pop("year"))

In [193]:
df_merged["avg_crimes"] = df_merged.iloc[:, 2:-4].mean(axis=1)      # [:, 2:-2] quiero -> todas las filas, desde la 2da hasta la penultima columna

In [194]:
df_merged = delete_sub_crimes(df_merged)

In [195]:
df_merged["years_from_today"] = 2024 - df_merged["year"]

In [196]:
df_poblacion = pd.read_csv("data/cleaned_pop.csv")


df_poblacion.drop(["Nacional", "Sexo"], inplace=True, axis=1)

regions_pop_version = {
    "01 Andalucía": 0,
    "02 Aragón": 1,
    "03 Asturias Principado de": 2,
    "04 Balears Illes": 3,
    "06 Cantabria": 4,
    "05 Canarias": 5,
    "08 Castilla - La Mancha": 6,
    "07 Castilla y León": 7,
    "09 Cataluña": 8,
    "18 Ceuta": 9,
    "19 Melilla": 10,
    "10 Comunitat Valenciana": 11,
    "11 Extremadura": 12,
    "12 Galicia": 13,
    "13 Madrid Comunidad de": 14,
    "14 Murcia Región de": 15,
    "15 Navarra Comunidad Foral de": 16,
    "16 País Vasco": 17,
    "17 Rioja La": 18
}


df_poblacion["region"] = df_poblacion["region"].replace(regions_pop_version)

C:\Users\VSPC\AppData\Local\Temp\ipykernel_9232\1471067258.py:29: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_poblacion["region"] = df_poblacion["region"].replace(regions_pop_version)

In [197]:
df_poblacion

     region  year      Total
0         0  2019  8.414.240
1         0  2018  8.384.408
2         0  2017  8.379.820
3         0  2016  8.388.107
4         0  2015  8.399.043
..      ...   ...        ...
185      10  2014     84.509
186      10  2013     83.679
187      10  2012     80.802
188      10  2011     78.476
189      10  2010     76.034

[190 rows x 3 columns]

In [198]:
df_merged = df_merged.merge(df_poblacion, on=["region", "year"])

df_merged.rename(columns={"Total": "population"}, inplace=True)

In [199]:
# Verifica los resultados
df_merged

,year,region,1_against_people,2_against_freedom,3_sexual_freedom,4_family_relationships,5_property_crimes,6_collective_security,7_forgeries,8_public_administration,9_justice_administration,Latitude,Longitude,avg_crimes,years_from_today,population
0,2019,0,37130,25751,2510,1503,239711,15094,3988,93,6728,37.3873,-5.9869,17723.219512,5,8.414.240
1,2019,1,4760,2276,330,161,31651,1360,446,3,799,41.6488,-0.8891,2249.902439,5,1.319.291
2,2019,2,3368,1872,193,99,19066,1205,220,6,567,43.3619,-5.8494,1429.390244,5,1.022.800
3,2019,3,8110,4718,743,188,58274,2880,716,11,1095,39.5712,2.6466,4082.146341,5,1.149.460
4,2019,5,12396,9328,907,639,64716,3439,1114,17,1721,28.2916,-16.6291,4960.829268,5,2.153.389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,2010,16,2726,675,130,82,13770,1059,259,21,235,42.6954,-1.6761,977.414634,14,636.924
186,2010,17,11792,4257,417,337,65555,3241,543,25,1170,43.2630,-2.9349,4515.878049,14,2.178.339
187,2010,18,1695,170,49,31,6555,519,54,0,137,42.2871,-2.5396,484.804878,14,322.415
188,2010,9,833,277,18,31,3053,1381,53,2,101,35.8894,-5.3198,300.804878,14,80.579
189,2010,10,1011,126,38,30,2810,304,42,1,70,35.2930,-2.9387,237.951220,14,76.034

In [200]:
df_merged.columns

Index(['year', 'region', '1_against_people', '2_against_freedom',
       '3_sexual_freedom', '4_family_relationships', '5_property_crimes',
       '6_collective_security', '7_forgeries', '8_public_administration',
       '9_justice_administration', 'Latitude', 'Longitude', 'avg_crimes',
       'years_from_today', 'population'],
      dtype='object')

In [201]:


crime_values = ['1_against_people', '2_against_freedom',
       '3_sexual_freedom', '4_family_relationships', '5_property_crimes',
       '6_collective_security', '7_forgeries', '8_public_administration',
       '9_justice_administration']

In [202]:
df_unpivot = pd.melt(df_merged, id_vars=['year', 'region', 'Latitude', 'Longitude', 'population'], value_vars=crime_values)

df_unpivot

,year,region,Latitude,Longitude,population,variable,value
0,2019,0,37.3873,-5.9869,8.414.240,1_against_people,37130
1,2019,1,41.6488,-0.8891,1.319.291,1_against_people,4760
2,2019,2,43.3619,-5.8494,1.022.800,1_against_people,3368
3,2019,3,39.5712,2.6466,1.149.460,1_against_people,8110
4,2019,5,28.2916,-16.6291,2.153.389,1_against_people,12396
...,...,...,...,...,...,...,...
1705,2010,16,42.6954,-1.6761,636.924,9_justice_administration,235
1706,2010,17,43.2630,-2.9349,2.178.339,9_justice_administration,1170
1707,2010,18,42.2871,-2.5396,322.415,9_justice_administration,137
1708,2010,9,35.8894,-5.3198,80.579,9_justice_administration,101
1709,2010,10,35.2930,-2.9387,76.034,9_justice_administration,70

In [203]:
df_unpivot_transformed = df_unpivot.copy()

for crime in crime_values:
    column_name = f'{crime}_indicator'
    df_unpivot_transformed[column_name] = (df_unpivot_transformed['variable'] == crime).astype(int)

df_unpivot_transformed

,year,region,Latitude,Longitude,population,variable,value,1_against_people_indicator,2_against_freedom_indicator,3_sexual_freedom_indicator,4_family_relationships_indicator,5_property_crimes_indicator,6_collective_security_indicator,7_forgeries_indicator,8_public_administration_indicator,9_justice_administration_indicator
0,2019,0,37.3873,-5.9869,8.414.240,1_against_people,37130,1,0,0,0,0,0,0,0,0
1,2019,1,41.6488,-0.8891,1.319.291,1_against_people,4760,1,0,0,0,0,0,0,0,0
2,2019,2,43.3619,-5.8494,1.022.800,1_against_people,3368,1,0,0,0,0,0,0,0,0
3,2019,3,39.5712,2.6466,1.149.460,1_against_people,8110,1,0,0,0,0,0,0,0,0
4,2019,5,28.2916,-16.6291,2.153.389,1_against_people,12396,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1705,2010,16,42.6954,-1.6761,636.924,9_justice_administration,235,0,0,0,0,0,0,0,0,1
1706,2010,17,43.2630,-2.9349,2.178.339,9_justice_administration,1170,0,0,0,0,0,0,0,0,1
1707,2010,18,42.2871,-2.5396,322.415,9_justice_administration,137,0,0,0,0,0,0,0,0,1
1708,2010,9,35.8894,-5.3198,80.579,9_justice_administration,101,0,0,0,0,0,0,0,0,1
1709,2010,10,35.2930,-2.9387,76.034,9_justice_administration,70,0,0,0,0,0,0,0,0,1

In [204]:
df_try_minus_years = df_unpivot_transformed 

df_previous_year = df_unpivot_transformed.copy()
df_previous_year['year'] += 1 
df_previous_year = df_previous_year[['year', 'region', 'variable', 'value']]
df_previous_year.rename(columns={'value': 'values_year_minus_1'}, inplace=True)

df_try_minus_years = pd.merge(
    df_try_minus_years,
    df_previous_year,
    on=['year', 'region', 'variable'],
    how='left'
)

df_try_minus_years

,year,region,Latitude,Longitude,population,variable,value,1_against_people_indicator,2_against_freedom_indicator,3_sexual_freedom_indicator,4_family_relationships_indicator,5_property_crimes_indicator,6_collective_security_indicator,7_forgeries_indicator,8_public_administration_indicator,9_justice_administration_indicator,values_year_minus_1
0,2019,0,37.3873,-5.9869,8.414.240,1_against_people,37130,1,0,0,0,0,0,0,0,0,35043.0
1,2019,1,41.6488,-0.8891,1.319.291,1_against_people,4760,1,0,0,0,0,0,0,0,0,4474.0
2,2019,2,43.3619,-5.8494,1.022.800,1_against_people,3368,1,0,0,0,0,0,0,0,0,3159.0
3,2019,3,39.5712,2.6466,1.149.460,1_against_people,8110,1,0,0,0,0,0,0,0,0,7545.0
4,2019,5,28.2916,-16.6291,2.153.389,1_against_people,12396,1,0,0,0,0,0,0,0,0,11805.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1705,2010,16,42.6954,-1.6761,636.924,9_justice_administration,235,0,0,0,0,0,0,0,0,1,NaN
1706,2010,17,43.2630,-2.9349,2.178.339,9_justice_administration,1170,0,0,0,0,0,0,0,0,1,NaN
1707,2010,18,42.2871,-2.5396,322.415,9_justice_administration,137,0,0,0,0,0,0,0,0,1,NaN
1708,2010,9,35.8894,-5.3198,80.579,9_justice_administration,101,0,0,0,0,0,0,0,0,1,NaN
1709,2010,10,35.2930,-2.9387,76.034,9_justice_administration,70,0,0,0,0,0,0,0,0,1,NaN

In [205]:
df_previous_year_2 = df_unpivot_transformed.copy()
df_previous_year_2['year'] += 2  
df_previous_year_2 = df_previous_year_2[['year', 'region', 'variable', 'value']]
df_previous_year_2.rename(columns={'value': 'values_year_minus_2'}, inplace=True)

df_try_minus_years = pd.merge(
    df_try_minus_years,
    df_previous_year_2,
    on=['year', 'region', 'variable'],
    how='left'
)

df_previous_year_3 = df_unpivot_transformed.copy()
df_previous_year_3['year'] += 3  
df_previous_year_3 = df_previous_year_3[['year', 'region', 'variable', 'value']]
df_previous_year_3.rename(columns={'value': 'values_year_minus_3'}, inplace=True)

df_try_minus_years = pd.merge(
    df_try_minus_years,
    df_previous_year_3,
    on=['year', 'region', 'variable'],
    how='left'
)

df_try_minus_years

,year,region,Latitude,Longitude,population,variable,value,1_against_people_indicator,2_against_freedom_indicator,3_sexual_freedom_indicator,4_family_relationships_indicator,5_property_crimes_indicator,6_collective_security_indicator,7_forgeries_indicator,8_public_administration_indicator,9_justice_administration_indicator,values_year_minus_1,values_year_minus_2,values_year_minus_3
0,2019,0,37.3873,-5.9869,8.414.240,1_against_people,37130,1,0,0,0,0,0,0,0,0,35043.0,35087.0,33661.0
1,2019,1,41.6488,-0.8891,1.319.291,1_against_people,4760,1,0,0,0,0,0,0,0,0,4474.0,4146.0,4005.0
2,2019,2,43.3619,-5.8494,1.022.800,1_against_people,3368,1,0,0,0,0,0,0,0,0,3159.0,3160.0,3239.0
3,2019,3,39.5712,2.6466,1.149.460,1_against_people,8110,1,0,0,0,0,0,0,0,0,7545.0,7096.0,6609.0
4,2019,5,28.2916,-16.6291,2.153.389,1_against_people,12396,1,0,0,0,0,0,0,0,0,11805.0,11744.0,11021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1705,2010,16,42.6954,-1.6761,636.924,9_justice_administration,235,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN
1706,2010,17,43.2630,-2.9349,2.178.339,9_justice_administration,1170,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN
1707,2010,18,42.2871,-2.5396,322.415,9_justice_administration,137,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN
1708,2010,9,35.8894,-5.3198,80.579,9_justice_administration,101,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN
1709,2010,10,35.2930,-2.9387,76.034,9_justice_administration,70,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN

In [206]:
df_values = df_try_minus_years.drop(columns=['variable'])

df_values = df_values.rename(columns={'value':'values_year'})

df_values

,year,region,Latitude,Longitude,population,values_year,1_against_people_indicator,2_against_freedom_indicator,3_sexual_freedom_indicator,4_family_relationships_indicator,5_property_crimes_indicator,6_collective_security_indicator,7_forgeries_indicator,8_public_administration_indicator,9_justice_administration_indicator,values_year_minus_1,values_year_minus_2,values_year_minus_3
0,2019,0,37.3873,-5.9869,8.414.240,37130,1,0,0,0,0,0,0,0,0,35043.0,35087.0,33661.0
1,2019,1,41.6488,-0.8891,1.319.291,4760,1,0,0,0,0,0,0,0,0,4474.0,4146.0,4005.0
2,2019,2,43.3619,-5.8494,1.022.800,3368,1,0,0,0,0,0,0,0,0,3159.0,3160.0,3239.0
3,2019,3,39.5712,2.6466,1.149.460,8110,1,0,0,0,0,0,0,0,0,7545.0,7096.0,6609.0
4,2019,5,28.2916,-16.6291,2.153.389,12396,1,0,0,0,0,0,0,0,0,11805.0,11744.0,11021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1705,2010,16,42.6954,-1.6761,636.924,235,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN
1706,2010,17,43.2630,-2.9349,2.178.339,1170,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN
1707,2010,18,42.2871,-2.5396,322.415,137,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN
1708,2010,9,35.8894,-5.3198,80.579,101,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN
1709,2010,10,35.2930,-2.9387,76.034,70,0,0,0,0,0,0,0,0,1,NaN,NaN,NaN

In [207]:
df_total_values = df_values.dropna(subset=['values_year_minus_1', 'values_year_minus_2', 'values_year_minus_3'])

df_total_values

,year,region,Latitude,Longitude,population,values_year,1_against_people_indicator,2_against_freedom_indicator,3_sexual_freedom_indicator,4_family_relationships_indicator,5_property_crimes_indicator,6_collective_security_indicator,7_forgeries_indicator,8_public_administration_indicator,9_justice_administration_indicator,values_year_minus_1,values_year_minus_2,values_year_minus_3
0,2019,0,37.3873,-5.9869,8.414.240,37130,1,0,0,0,0,0,0,0,0,35043.0,35087.0,33661.0
1,2019,1,41.6488,-0.8891,1.319.291,4760,1,0,0,0,0,0,0,0,0,4474.0,4146.0,4005.0
2,2019,2,43.3619,-5.8494,1.022.800,3368,1,0,0,0,0,0,0,0,0,3159.0,3160.0,3239.0
3,2019,3,39.5712,2.6466,1.149.460,8110,1,0,0,0,0,0,0,0,0,7545.0,7096.0,6609.0
4,2019,5,28.2916,-16.6291,2.153.389,12396,1,0,0,0,0,0,0,0,0,11805.0,11744.0,11021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1648,2013,16,42.6954,-1.6761,644.477,198,0,0,0,0,0,0,0,0,1,234.0,230.0,235.0
1649,2013,17,43.2630,-2.9349,2.191.682,1470,0,0,0,0,0,0,0,0,1,1458.0,1357.0,1170.0
1650,2013,18,42.2871,-2.5396,322.027,115,0,0,0,0,0,0,0,0,1,147.0,141.0,137.0
1651,2013,9,35.8894,-5.3198,84.180,125,0,0,0,0,0,0,0,0,1,157.0,84.0,101.0
1652,2013,10,35.2930,-2.9387,83.679,43,0,0,0,0,0,0,0,0,1,69.0,67.0,70.0

In [209]:
# Tabla final

df_total_values.to_csv('df_total_values.csv', index=False)